# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(839, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox_11 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_11.setGeometry(QtCore.QRect(210, 90, 42, 22))
        self.spinBox_11.setMaximum(1)
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_12 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_12.setGeometry(QtCore.QRect(290, 90, 42, 22))
        self.spinBox_12.setMaximum(1)
        self.spinBox_12.setObjectName("spinBox_12")
        self.spinBox_21 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_21.setGeometry(QtCore.QRect(130, 130, 42, 22))
        self.spinBox_21.setMaximum(1)
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_22 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_22.setGeometry(QtCore.QRect(290, 130, 42, 22))
        self.spinBox_22.setMaximum(1)
        self.spinBox_22.setObjectName("spinBox_22")
        self.spinBox_31 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_31.setGeometry(QtCore.QRect(130, 170, 42, 22))
        self.spinBox_31.setMaximum(1)
        self.spinBox_31.setObjectName("spinBox_31")
        self.spinBox_32 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_32.setGeometry(QtCore.QRect(210, 170, 42, 22))
        self.spinBox_32.setMaximum(1)
        self.spinBox_32.setObjectName("spinBox_32")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 55, 16))
        self.label.setObjectName("label")
        self.spinBox_14 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_14.setGeometry(QtCore.QRect(450, 90, 42, 22))
        self.spinBox_14.setMaximum(1)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_23 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_23.setGeometry(QtCore.QRect(370, 130, 42, 22))
        self.spinBox_23.setMaximum(1)
        self.spinBox_23.setObjectName("spinBox_23")
        self.spinBox_13 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_13.setGeometry(QtCore.QRect(370, 90, 42, 22))
        self.spinBox_13.setMaximum(1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_33 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_33.setGeometry(QtCore.QRect(370, 170, 42, 22))
        self.spinBox_33.setMaximum(1)
        self.spinBox_33.setObjectName("spinBox_33")
        self.spinBox_34 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_34.setGeometry(QtCore.QRect(450, 170, 42, 22))
        self.spinBox_34.setMaximum(1)
        self.spinBox_34.setObjectName("spinBox_34")
        self.spinBox_24 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_24.setGeometry(QtCore.QRect(450, 130, 42, 22))
        self.spinBox_24.setMaximum(1)
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_42 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_42.setGeometry(QtCore.QRect(210, 210, 42, 22))
        self.spinBox_42.setMaximum(1)
        self.spinBox_42.setObjectName("spinBox_42")
        self.spinBox_51 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_51.setGeometry(QtCore.QRect(130, 250, 42, 22))
        self.spinBox_51.setMaximum(1)
        self.spinBox_51.setObjectName("spinBox_51")
        self.spinBox_54 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_54.setGeometry(QtCore.QRect(370, 250, 42, 22))
        self.spinBox_54.setMaximum(1)
        self.spinBox_54.setObjectName("spinBox_54")
        self.spinBox_41 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_41.setGeometry(QtCore.QRect(130, 210, 42, 22))
        self.spinBox_41.setMaximum(1)
        self.spinBox_41.setObjectName("spinBox_41")
        self.spinBox_52 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_52.setGeometry(QtCore.QRect(210, 250, 42, 22))
        self.spinBox_52.setMaximum(1)
        self.spinBox_52.setObjectName("spinBox_52")
        self.spinBox_44 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_44.setGeometry(QtCore.QRect(450, 210, 42, 22))
        self.spinBox_44.setMaximum(1)
        self.spinBox_44.setObjectName("spinBox_44")
        self.spinBox_53 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_53.setGeometry(QtCore.QRect(290, 250, 42, 22))
        self.spinBox_53.setMaximum(1)
        self.spinBox_53.setObjectName("spinBox_53")
        self.spinBox_43 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_43.setGeometry(QtCore.QRect(290, 210, 42, 22))
        self.spinBox_43.setMaximum(1)
        self.spinBox_43.setObjectName("spinBox_43")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 50, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 50, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 50, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 90, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 130, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 170, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 250, 55, 16))
        self.label_10.setObjectName("label_10")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(450, 250, 41, 21))
        self.textBrowser_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setOverwriteMode(False)
        self.textBrowser_2.setTabStopDistance(80.0)
        self.textBrowser_2.setAcceptRichText(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setEnabled(True)
        self.textBrowser_3.setGeometry(QtCore.QRect(370, 210, 41, 21))
        self.textBrowser_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setOverwriteMode(False)
        self.textBrowser_3.setTabStopDistance(80.0)
        self.textBrowser_3.setAcceptRichText(True)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setEnabled(True)
        self.textBrowser_4.setGeometry(QtCore.QRect(290, 170, 41, 21))
        self.textBrowser_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setOverwriteMode(False)
        self.textBrowser_4.setTabStopDistance(80.0)
        self.textBrowser_4.setAcceptRichText(True)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setEnabled(True)
        self.textBrowser_5.setGeometry(QtCore.QRect(210, 130, 41, 21))
        self.textBrowser_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setOverwriteMode(False)
        self.textBrowser_5.setTabStopDistance(80.0)
        self.textBrowser_5.setAcceptRichText(True)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setEnabled(True)
        self.textBrowser_6.setGeometry(QtCore.QRect(130, 90, 41, 21))
        self.textBrowser_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setOverwriteMode(False)
        self.textBrowser_6.setTabStopDistance(80.0)
        self.textBrowser_6.setAcceptRichText(True)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.sum_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.sum_1.setEnabled(True)
        self.sum_1.setGeometry(QtCore.QRect(530, 90, 41, 21))
        self.sum_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_1.setOverwriteMode(False)
        self.sum_1.setTabStopDistance(80.0)
        self.sum_1.setAcceptRichText(True)
        self.sum_1.setObjectName("sum_1")
        self.sum_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.sum_2.setEnabled(True)
        self.sum_2.setGeometry(QtCore.QRect(530, 130, 41, 21))
        self.sum_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_2.setOverwriteMode(False)
        self.sum_2.setTabStopDistance(80.0)
        self.sum_2.setAcceptRichText(True)
        self.sum_2.setObjectName("sum_2")
        self.sum_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.sum_3.setEnabled(True)
        self.sum_3.setGeometry(QtCore.QRect(530, 170, 41, 21))
        self.sum_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_3.setOverwriteMode(False)
        self.sum_3.setTabStopDistance(80.0)
        self.sum_3.setAcceptRichText(True)
        self.sum_3.setObjectName("sum_3")
        self.sum_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.sum_4.setEnabled(True)
        self.sum_4.setGeometry(QtCore.QRect(530, 210, 41, 21))
        self.sum_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_4.setOverwriteMode(False)
        self.sum_4.setTabStopDistance(80.0)
        self.sum_4.setAcceptRichText(True)
        self.sum_4.setObjectName("sum_4")
        self.sum_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.sum_5.setEnabled(True)
        self.sum_5.setGeometry(QtCore.QRect(530, 250, 41, 21))
        self.sum_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sum_5.setOverwriteMode(False)
        self.sum_5.setTabStopDistance(80.0)
        self.sum_5.setAcceptRichText(True)
        self.sum_5.setObjectName("sum_5")
        self.W_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_1.setEnabled(True)
        self.W_1.setGeometry(QtCore.QRect(610, 90, 41, 21))
        self.W_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_1.setOverwriteMode(False)
        self.W_1.setTabStopDistance(80.0)
        self.W_1.setAcceptRichText(True)
        self.W_1.setObjectName("W_1")
        self.W_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_2.setEnabled(True)
        self.W_2.setGeometry(QtCore.QRect(610, 130, 41, 21))
        self.W_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_2.setOverwriteMode(False)
        self.W_2.setTabStopDistance(80.0)
        self.W_2.setAcceptRichText(True)
        self.W_2.setObjectName("W_2")
        self.W_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_3.setEnabled(True)
        self.W_3.setGeometry(QtCore.QRect(610, 170, 41, 21))
        self.W_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_3.setOverwriteMode(False)
        self.W_3.setTabStopDistance(80.0)
        self.W_3.setAcceptRichText(True)
        self.W_3.setObjectName("W_3")
        self.W_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_4.setEnabled(True)
        self.W_4.setGeometry(QtCore.QRect(610, 210, 41, 21))
        self.W_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_4.setOverwriteMode(False)
        self.W_4.setTabStopDistance(80.0)
        self.W_4.setAcceptRichText(True)
        self.W_4.setObjectName("W_4")
        self.W_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_5.setEnabled(True)
        self.W_5.setGeometry(QtCore.QRect(610, 250, 41, 21))
        self.W_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_5.setOverwriteMode(False)
        self.W_5.setTabStopDistance(80.0)
        self.W_5.setAcceptRichText(True)
        self.W_5.setObjectName("W_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 300, 55, 16))
        self.label_11.setObjectName("label_11")
        self.output = QtWidgets.QTextBrowser(self.centralwidget)
        self.output.setEnabled(True)
        self.output.setGeometry(QtCore.QRect(130, 300, 521, 21))
        self.output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output.setOverwriteMode(False)
        self.output.setTabStopDistance(80.0)
        self.output.setAcceptRichText(True)
        self.output.setPlaceholderText("")
        self.output.setObjectName("output")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(530, 50, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(620, 50, 55, 16))
        self.label_13.setObjectName("label_13")
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setGeometry(QtCore.QRect(710, 100, 93, 41))
        self.button_ok.setObjectName("button_ok")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(710, 160, 93, 41))
        self.button_clear.setObjectName("button_clear")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(710, 220, 93, 41))
        self.button_quit.setObjectName("button_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Лондон"))
        self.label_2.setText(_translate("MainWindow", "Пекин"))
        self.label_3.setText(_translate("MainWindow", "Сеул"))
        self.label_4.setText(_translate("MainWindow", "Владивосток"))
        self.label_5.setText(_translate("MainWindow", "Тель-Авив"))
        self.label_6.setText(_translate("MainWindow", "Лондон"))
        self.label_7.setText(_translate("MainWindow", "Пекин"))
        self.label_8.setText(_translate("MainWindow", "Сеул"))
        self.label_9.setText(_translate("MainWindow", "Владивосток"))
        self.label_10.setText(_translate("MainWindow", "Тель-Авив"))
        self.textBrowser_2.setPlaceholderText(_translate("MainWindow", "   -"))
        self.textBrowser_3.setPlaceholderText(_translate("MainWindow", "   -"))
        self.textBrowser_4.setPlaceholderText(_translate("MainWindow", "   -"))
        self.textBrowser_5.setPlaceholderText(_translate("MainWindow", "   -"))
        self.textBrowser_6.setPlaceholderText(_translate("MainWindow", "   -"))
        self.sum_1.setPlaceholderText(_translate("MainWindow", "   -"))
        self.sum_2.setPlaceholderText(_translate("MainWindow", "   -"))
        self.sum_3.setPlaceholderText(_translate("MainWindow", "   -"))
        self.sum_4.setPlaceholderText(_translate("MainWindow", "   -"))
        self.sum_5.setPlaceholderText(_translate("MainWindow", "   -"))
        self.W_1.setPlaceholderText(_translate("MainWindow", "   -"))
        self.W_2.setPlaceholderText(_translate("MainWindow", "   -"))
        self.W_3.setPlaceholderText(_translate("MainWindow", "   -"))
        self.W_4.setPlaceholderText(_translate("MainWindow", "   -"))
        self.W_5.setPlaceholderText(_translate("MainWindow", "   -"))
        self.label_11.setText(_translate("MainWindow", "Ответ"))
        self.label_12.setText(_translate("MainWindow", "Сумма"))
        self.label_13.setText(_translate("MainWindow", "W"))
        self.button_ok.setText(_translate("MainWindow", "Ок"))
        self.button_clear.setText(_translate("MainWindow", "Сброс"))
        self.button_quit.setText(_translate("MainWindow", "Выход"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
